### ISSUE TITLE
Providers on home page

### ISSUE THREAD

**Issue by The-Schwiz** [Sophack/firstGroupProject#3]
When resizing screen, "providers" overflow onto the search bar 

![Screenshot 2022-11-16 at 3 22 05 PM](https://user-images.githubusercontent.com/113313870/202286590-567093b7-da27-43a4-9e39-964c13824ad1.png)

**Comment by Sophack** [comment]
I was able to fix this issue by adding media queries & setting top/bottom margins. 

I tested it by playing around with the width & it works on my end, let me know if you guys run into issues on yours!
![issue1](https://user-images.githubusercontent.com/114966651/202326494-d0816d3d-83a1-4168-9051-3c0952105100.jpg)
